### ISSUE TITLE
 connect ECONNREFUSED 127.0.0.1:30080

### ISSUE THREAD

**Issue by StoleMyIceCream** [sean-perkins/angular-electron-seed#10]
I get the following 2 errors when I did npm start (didn't change anything yet):

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: connect ECONNREFUSED 127.0.0.1:30080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)`

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (eventsjs:188:7)
    at TCP._handle.close [as _onclose] (net.js:501:12) `

Operating system: Debian
Electron: 5.0.4

**Comment by alejandrocena** [comment]
I have the same Issue, I think it's related to an **electron-connect** library problem. Here  will find the issue
[electron-connect issue](https://github.com/Quramy/electron-connect/issues/74)
If you agree with this idea. Please, vote it.

**Comment by awmleer** [comment]
Is this issue duplicated with #6 ?

**Comment by arthursp** [comment]
The problem is not happening with watch process

**Comment by sean-perkins** [comment]
As mentioned, same issue as #6, but I would love for the up-stream project to have a solution for it. Unfortunately with the order of how it bootstraps, I haven't found a good way to resolve this issue within the seed. It's not an "error" as long as you set-up the watch. 

I may be able to write a custom task that waits for the app to bootstrap, prior to attempting to connect. But that will be a few weeks out at the earliest. 

I'll leave this issue open as it constantly is being re-reported, although the closed issues reference it.

**Comment by StoleMyIceCream** [comment]
Thank you 😀

**Comment by ssreekanth** [comment]
The reason you are seeing this error is - `npm start` script doesn't seem to be starting `electron-connect's server` anywhere.

Also, on a different note, it appears `npm run watch` script seems to be launching electron app twice - first from `npm run build.watch` (as a result of electron-connect's server) and again from `npm run start.electron`. There is no need for `npm run start.electron` at the end of the `npm run watch` script.

Hope that helps..!!

**Comment by flamusdiu** [comment]
@ssreekanth yup, I have noticed this as well. I guess checking to see if the server is started (then starting it) or just skipping creating the client.

Though, I am getting `\node_modules\electron\dist\electron.exe: bad option: -r process` when I run `npm start watch` in my current project which includes PouchDB.

**Comment by abhishekbhalani** [comment]
@sean-perkins 
Did the issue fixed or not? I am facing the ECONNREFUSED error while running.

please update me.

**Comment by abalad** [comment]
same here
